---
title: "CCBH Mental Health Outpatient Appointment Availability Map"
author: "Crystal Zang"
date: '2023-02-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
library(sf)
library(mapview)
library(RColorBrewer)
library(leafpop)

data <- read.csv("data/data.csv")
```

```{r echo=FALSE}
data_plot <- data%>%
  filter(!is.na(long))%>%
  mutate( AppointmentAvailability = ifelse(liveperson_appt_available ==T, "Available(Live Person)", 
                                           ifelse(voicemail_appt_available==T, "Available(Voicemail)", "Not Available")))%>%
  mutate(AppointmentAvailability = ifelse(is.na(AppointmentAvailability), "Not Available", AppointmentAvailability))%>%
  select(-liveperson_appt_available, -voicemail_appt_available)

data_sf <- st_as_sf(data_plot, coords = c("long", "lat"))

st_crs(data_sf) <- 4326 # we can use EPSG as numeric here

#mapviewOptions()

mapview(data_sf, xcol = "long", ycol = "lat",
        zcol = "AppointmentAvailability" , 
       
        popup = popupTable(data_sf),
        crs = 4326, grid = FALSE)

```
